### ISSUE TITLE
Disable the prompt when hovering

### ISSUE THREAD

**Issue by zhouyc98** [AlanRynne/ifc-syntax#2]
Hello,
Currently, when I hover my cursor over any word, it will show "I am a hover!" like the image below.
![image](https://user-images.githubusercontent.com/36097684/69476382-33d5b600-0e14-11ea-9eeb-d54e29412a46.png)
I think it will be better to disable the prompt.

Finally, thanks for your great extension, it helps me a lot!

**Comment by AlanRynne** [comment]
Oops!! One of my initial tests got through... Sorry!! Will delete it this weekend and push a new update to the marketplace.
Thank you very much for the heads up!

**Comment by AlanRynne** [comment]
Fixed in  PR #4 👍 . Will publish new version in a couple of minutes. I'm closing this issue since I'm considering it "resolved". Feel free to create new issues to suggest any upgrades, commands or additions you might like and I will do my best to implement them.

**Comment by zhouyc98** [comment]
Alright, thank you!
