### ISSUE TITLE
Cannot apply comment style in data section

### ISSUE THREAD

**Issue by zhouyc98** [AlanRynne/ifc-syntax#6]
Hey!

I found that when I do some comments in the data section, the style will not change to the comment style.
As shown in the figure below, line 2833 should have a green foreground color, but actually not.

![image](https://user-images.githubusercontent.com/36097684/70716081-97257a80-1d26-11ea-9a96-446341aea142.png)

**Comment by AlanRynne** [comment]
Hmmm... 🤔 interesting! Thank you for pointing that out, it is very helpful to know where the subtle bugs are hiding!! I'll do some checks this weekend to find a solution. Hopefully it will be a quick fix! 🤞

**Comment by zhouyc98** [comment]
Thank you in advance 😁

**Comment by AlanRynne** [comment]
Seems like I managed to fix it, although i haven't properly tested all the possible test cases. I'll push a new update to the marketplace shortly
![image](https://user-images.githubusercontent.com/2316535/70870233-e7077a00-1f90-11ea-8e76-406663bf2b33.png)

**Comment by AlanRynne** [comment]
New version 0.1.4 is live now. Thanks again @Zhou-Yucheng for pointing out the bug (and for using the extension!! 👍) Anything else you might find, miss or want to suggest, I am always open to considering new ideas.

Im closing this issue for now but feel free to re-open or open a new one for any other topic.

**Comment by zhouyc98** [comment]
It works now!
Thank you 👍
